<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Note: Adjust TargetFramework to the one required by your AutoCAD version (e.g. net48) -->
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.16" />
    </ItemGroup>

</Project>
